export { createLoodiSupabaseClient } from './client.js'
export type { AuthStorage, LoodiSupabaseClientOptions } from './client.js'
export { DEFAULT_RESERVED_HANDLES, HANDLE_PATTERN, RESERVED_MODULE_NAMES, isValidHandle, normalizeHandle } from './handles.js'
export { resolveAuthState } from './auth-state.js'
export type { AuthProfile, AuthState } from './auth-state.js'
export { abandonIncompleteAccount, completeAuthCallback, linkGoogleIdentity, refreshSessionUser, signInWithGoogle, signInWithMagicLink, signOut, unlinkGoogleIdentity, updateEmail, updateProfileColor } from './auth-service.js'
export { AuthProvider, useAuth } from './AuthProvider.js'
export type { AuthContextValue, AuthSession } from './AuthProvider.js'
export { toUserFacingAuthError } from './errors.js'
